Implement preferences view
xenharmonic-devs/scale-workshop pull request #44
Opened 2022-05-31 18:54 UTC by frostburn

Co-authored-by: Sean Archibald <sean@sevish.com>

2022-06-19 11:06 UTC, SeanArchibald requested changes
`<div class="synth">`
Looks like the wrong class name got in here. Everything else looks fine, and happy to merge this to main after changing the class name to prefs or preferences or something similar.

2022-06-19 11:13 UTC, frostburn commented
@SeanArchibald I must've messed up the assignments/reviewers/communication. This was intended for you to continue the work on.

2022-07-14 07:49 UTC, frostburn commented
Ready for review.

2022-07-23 16:20 UTC, SeanArchibald approved these changes

2022-07-23 16:21 UTC, merged